version: 2.1
orbs:
  architect: giantswarm/architect@0.5.3

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test-microerror
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
